# This script has been created to retrieve the latest archive
# generated by the Develop bot on CI Server Bob.

# It copies the latest archive in the current directory.
# The account used is 'xcodeserver'.
# The password for this account will be asked every time this script is executed.

# /!\ This script only works from within Candyspace's network.

CI_SERVER_URL=bob.local
USERNAME=xcodeserver
ARCHIVE_NAME=ITV_Player.xcarchive
ARCHIVE_PATH=/Users/${USERNAME}/LatestReleaseArchive/${ARCHIVE_NAME}

scp -r ${USERNAME}@${CI_SERVER_URL}:${ARCHIVE_PATH} . ; open ${ARCHIVE_NAME}
